<?xml version="1.0"?>
<robot name="d01"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <xacro:property name="body_from_ground" value="0.6" />
    <xacro:property name="body_height" value="1.3" />
    <xacro:property name="body_length" value="2.02"/>
    <xacro:property name="body_width" value="1.7"/>


    <link name="base_link">
        <visual>
            <origin xyz="0.0  0.0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="White"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="${body_width*body_width/12+body_height*body_height/12}" ixy="0.0" ixz="0.0" iyy="${body_length*body_length/12+body_height*body_height/12}" iyz="0.0" izz="${body_length*body_length/12+body_width*body_width/12}"/>
        </inertial>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <!-->
    <link name="wheel_link">
        <visual>
            <origin xyz="0 -1 0.7" rpy="1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.7" length="0.3"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 -1 0.7" rpy="1.57 0 0"/>
            <mass value="1"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
        </inertial>
        <collision>
            <origin xyz="0 -1 0.7" rpy="1.57 0 0 " />
            <geometry>
                <cylinder radius="0.7" length="0.3"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="wheel_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <joint name="wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_link"/>
        <origin xyz="1.5 -0.85 0.7" rpy="0 0 0"/>
        <axis xyz="0.0 0.0 1"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>
    <transmission name="$action_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel_joint" />
        <actuator name="action_wheel_joint_motor">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <link name="right_wheel_link">
        <visual>
            <origin xyz="0 1 0.7" rpy="1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.7" length="0.3"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 1 0.7" rpy="1.57 0 0"/>
            <mass value="1"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
        </inertial>
        <collision>
            <origin xyz="0 1 0.7" rpy="1.57 0 0 " />
            <geometry>
                <cylinder radius="0.7" length="0.3"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="wheel_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="1.5 0.85 0.7" rpy="0 0 0"/>
        <axis xyz="0.0 0.0 1"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>
    <transmission name="$right_action_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_wheel_joint" />
        <actuator name="right_action_wheel_joint_motor">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <-->
        <xacro:include filename="$(find diff_wheeled_robot_gazebo)/urdf/d01/d01_action_wheel.urdf.xacro"/>
        <xacro:action_wheel parent="base_link" name="leftfront" radius="0.7" length="0.3" flipY="-1" translateX="0.8" translateY="-0.9">
        </xacro:action_wheel>
        <xacro:action_wheel parent="base_link" name="rightfront" radius="0.7" length="0.3" flipY="-1" translateX="0.8" translateY="0.9">
        </xacro:action_wheel>
        <xacro:action_wheel parent="base_link" name="leftback" radius="0.7" length="0.3" flipY="-1" translateX="-0.8" translateY="-0.9">
        </xacro:action_wheel>
        <xacro:action_wheel parent="base_link" name="rightback" radius="0.7" length="0.3" flipY="-1" translateX="-0.8" translateY="0.9">
        </xacro:action_wheel>

        <gazebo>
            <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
                <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>false</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>false</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <leftJoint>leftfront_action_wheel_joint</leftJoint>
                <rightJoint>rightfront_action_wheel_joint</rightJoint>
                <wheelSeparation>${body_width}</wheelSeparation>
                <wheelDiameter>1.4</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>2.5</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame>
                <odometryTopic>odom</odometryTopic>
                <robotBaseFrame>base_footprint</robotBaseFrame>
            </plugin>
        </gazebo>


<xacro:property name="laser_plattform_width" value="0.12"/>
<xacro:property name="laser_plattform_length" value="0.12"/>
<xacro:property name="laser_plattform_height" value="0.6"/>
        <link name="laser_plattform_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${laser_plattform_width}  ${laser_plattform_length} ${laser_plattform_height}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <box size="0.12  0.12 0.2"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="${laser_plattform_width}  ${laser_plattform_length} ${laser_plattform_height}" rpy="0.0 0.0 0.0"/>
                <mass value="1"/>
                <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
            </inertial>
        </link>
        <joint name="laser_plattform_joint" type="fixed">
            <parent link="base_link"/>
            <child link="laser_plattform_link"/>
            <origin xyz="${body_length/2-laser_plattform_length/2} 0.0 ${body_height/2+laser_plattform_height/2}" rpy="0.0 0.0 0.0"/>
        </joint>


        <xacro:arg name="gpu" default="false"/>
        <xacro:property name="gpu" value="$(arg gpu)" />
        <xacro:arg name="organize_cloud" default="false"/>
        <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />
        <xacro:property name="base_radius_velodyne" value="0.0516"/>
        <xacro:include filename="$(find diff_wheeled_robot_gazebo)/urdf/VLP-16.urdf.xacro"/>
        <xacro:VLP-16 parent="laser_plattform_link" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="10" samples="440" gpu="${gpu}">
            <origin xyz="0 0 ${laser_plattform_height/2}" rpy="0 0 0" />
        </xacro:VLP-16>

    </robot>


